# Generated by Django 4.2.6 on 2023-10-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default=1, max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='password',
            new_name='wage',
        ),
        migrations.AddField(
            model_name='club',
            name='means',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='transferable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt',
            field=models.CharField(default='transfermarkt.fr', max_length=1000),
        ),
        migrations.AddField(
            model_name='club',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.division'),
        ),
    ]
