# Generated by Django 4.2.6 on 2024-01-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0003_rename_institution_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='foot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='transferable',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
