# Generated by Django 4.2.6 on 2024-01-24 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0004_remove_player_age_remove_player_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/agent/')),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='scout',
            name='agent',
        ),
        migrations.AddField(
            model_name='player',
            name='agent',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='created_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='foot',
            field=models.CharField(default='Droit', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='modified_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='other_pos',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='potential',
            field=models.CharField(default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='size',
            field=models.CharField(default=175, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='transferable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='wage',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.AddField(
            model_name='scout',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.agency'),
        ),
    ]
