# Generated by Django 4.2.6 on 2024-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0006_situation_delete_statut_rename_date_player_date_prop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='player',
            name='situation',
        ),
        migrations.AddField(
            model_name='player',
            name='situation',
            field=models.CharField(default='To Complete', max_length=500),
        ),
    ]
