# Generated by Django 4.2.6 on 2024-01-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0007_alter_player_first_name_alter_player_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='Player_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_prop',
        ),
        migrations.RemoveField(
            model_name='player',
            name='end_contract',
        ),
        migrations.RemoveField(
            model_name='player',
            name='end_mand',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='foot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='move_cond',
        ),
        migrations.RemoveField(
            model_name='player',
            name='note',
        ),
        migrations.RemoveField(
            model_name='player',
            name='other_pos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='potential',
        ),
        migrations.RemoveField(
            model_name='player',
            name='release',
        ),
        migrations.RemoveField(
            model_name='player',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='size',
        ),
        migrations.RemoveField(
            model_name='player',
            name='system',
        ),
        migrations.RemoveField(
            model_name='player',
            name='transfermarkt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wage',
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
