# Generated by Django 4.2.6 on 2024-01-24 16:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0008_rename_name_player_player_name_remove_player_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Player_name',
        ),
        migrations.AddField(
            model_name='player',
            name='agent',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='champ',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='FCA', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='comment',
            field=models.CharField(default='-', max_length=2000),
        ),
        migrations.AddField(
            model_name='player',
            name='created_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='date_prop',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='end_contract',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='end_mand',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='foot',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='modified_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='player',
            name='move_cond',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='note',
            field=models.CharField(default='R1', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='other_pos',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(default=612456789, max_length=10000),
        ),
        migrations.AddField(
            model_name='player',
            name='potential',
            field=models.CharField(default='R1', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='release',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='situation',
            field=models.CharField(default='4-4-2', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='size',
            field=models.CharField(default=175, max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='system',
            field=models.CharField(default='4-4-2', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt',
            field=models.CharField(default='transfermarkt.fr', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='wage',
            field=models.CharField(default=1200, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
