# Generated by Django 4.2.6 on 2024-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0011_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(default='Droit', max_length=500),
        ),
    ]
