# Generated by Django 4.2.6 on 2024-01-24 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0013_myuuidmodel_alter_player_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
