# Generated by Django 4.2.6 on 2024-01-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0016_rename_unique_id_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='id',
            new_name='unique_id',
        ),
    ]
