# Generated by Django 4.2.6 on 2024-01-25 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0018_rename_unique_id_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('system', models.CharField(max_length=500)),
                ('mentality', models.CharField(max_length=500)),
                ('actual', models.CharField(default='R-1', max_length=10)),
                ('financial', models.CharField(default='R-1', max_length=10)),
                ('potential', models.CharField(default='R-1', max_length=10)),
                ('note_totale', models.CharField(default='R-1', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Situation',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='note',
            new_name='note_tot',
        ),
        migrations.RemoveField(
            model_name='club',
            name='date',
        ),
        migrations.RemoveField(
            model_name='club',
            name='division',
        ),
        migrations.RemoveField(
            model_name='club',
            name='means',
        ),
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='Actual',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='Club',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='Financial',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='champ',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='date_crea',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
        migrations.AddField(
            model_name='club',
            name='date_mod',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
        migrations.AddField(
            model_name='club',
            name='note_totale',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='agency_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.agency'),
        ),
        migrations.AddField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='note_actuel',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='note_financ',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='champ',
            field=models.CharField(default='Inconnu', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='comment',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_prop',
            field=models.DateField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_mand',
            field=models.DateField(default=datetime.datetime(1899, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_pos',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='release',
            field=models.CharField(default='Inconnu', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='situation',
            field=models.CharField(default='To complete', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='system',
            field=models.CharField(default='Inconnu', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='wage',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.coach'),
        ),
    ]
