# Generated by Django 4.2.6 on 2024-01-25 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0019_coach_delete_situation_rename_note_player_note_tot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.coach'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.club'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='agency',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.agency'),
        ),
    ]
