# Generated by Django 4.2.6 on 2024-01-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0022_alter_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='comment',
            field=models.CharField(default='Inconnu', max_length=2000),
        ),
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(default='Inconnu', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_pos',
            field=models.CharField(default=models.CharField(default='Inconnu', max_length=50), max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='wage',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
    ]
