# Generated by Django 4.2.6 on 2024-01-25 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0023_alter_player_club_id_alter_player_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.club'),
        ),
    ]
