# Generated by Django 4.2.6 on 2024-01-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0024_alter_club_id_alter_player_club_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='id',
            new_name='ide',
        ),
    ]
