# Generated by Django 4.2.6 on 2024-01-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0025_rename_id_club_ide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='ide',
            new_name='id',
        ),
    ]
