# Generated by Django 4.2.6 on 2024-01-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0027_alter_player_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='agency_id',
        ),
    ]
