# Generated by Django 4.2.6 on 2024-01-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0029_rename_date_agency_date_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='situation',
            field=models.CharField(default='-', max_length=1500),
        ),
    ]
