# Generated by Django 4.2.6 on 2024-01-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0030_contact_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mod_by',
            new_name='mod',
        ),
    ]
