# Generated by Django 4.2.6 on 2024-01-25 23:09

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0032_alter_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='crea_by',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='agency',
            name='mod_by',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='agency',
            name='date_crea',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
