# Generated by Django 4.2.6 on 2024-01-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0034_alter_business_club_id_alter_player_agence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='agence_id',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.agency'),
        ),
    ]
