# Generated by Django 4.2.6 on 2024-01-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0035_alter_player_agence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='agence_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.agency'),
        ),
    ]
