# Generated by Django 4.2.6 on 2024-01-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0036_alter_player_agence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Actual',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='Financial',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='financial',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='note_totale',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='potential',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='note_actuel',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='note_financ',
            field=models.CharField(default='non calculable', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='potential',
            field=models.CharField(default='non calculable', max_length=10),
        ),
    ]
