# Generated by Django 4.2.6 on 2024-02-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0039_alter_player_note_tot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_prop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_contract',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_mand',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.ManyToManyField(to='wasserman_core.player')),
            ],
        ),
    ]
