# Generated by Django 4.2.6 on 2024-02-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0040_alter_player_birth_alter_player_date_prop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pos',
        ),
    ]
