# Generated by Django 4.2.6 on 2024-02-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0041_delete_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='Actual',
        ),
        migrations.RemoveField(
            model_name='club',
            name='Financial',
        ),
        migrations.AddField(
            model_name='coach',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_crea',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_mod',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='flexibility',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='mod_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='personnality',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='style',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mod_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agency',
            name='date_crea',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='date_mod',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='mod_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_mod',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mod_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.CharField(default='R0', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='created_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='financial',
            field=models.CharField(default='R0', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='mentality',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='note_totale',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='potential',
            field=models.CharField(default='R0', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='rating',
            field=models.CharField(default='R0', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='system',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='modified_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='situation',
            field=models.CharField(default='Inconnu', max_length=500),
        ),
        migrations.AlterField(
            model_name='scout',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='actual',
            field=models.CharField(default='R0', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='financial',
            field=models.CharField(default='R0', max_length=10),
        ),
    ]
