# Generated by Django 4.2.6 on 2024-02-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0042_remove_club_actual_remove_club_financial_coach_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='agent',
        ),
        migrations.AddField(
            model_name='player',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.contact'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.club'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pour', models.TextField(null=True)),
                ('competition', models.CharField(default='-', max_length=500)),
                ('date', models.DateField(blank=True)),
                ('note_actuelle', models.CharField(default='R0', max_length=5)),
                ('note_potentielle', models.CharField(default='R0', max_length=5)),
                ('commentaires', models.TextField()),
                ('contre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.player')),
            ],
        ),
    ]
