# Generated by Django 4.2.6 on 2024-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0044_report_poste_alter_player_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
