# Generated by Django 4.2.6 on 2024-03-01 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0045_report_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.CreateModel(
            name='InfoMercato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('info', models.TextField()),
                ('nature', models.CharField(blank=True, max_length=250)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.player')),
            ],
        ),
    ]
