# Generated by Django 4.2.6 on 2024-03-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0047_remove_club_club_type_remove_club_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='mod_by',
        ),
        migrations.AlterField(
            model_name='club',
            name='commentaires',
            field=models.TextField(),
        ),
    ]
