# Generated by Django 4.2.6 on 2024-03-01 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0048_remove_club_mod_by_alter_club_commentaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='mod_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_mod',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
