# Generated by Django 4.2.6 on 2024-03-01 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0049_club_mod_by_alter_club_date_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='contact_id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='date_mod',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='business',
            name='mod_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='scout',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_id',
            field=models.ManyToManyField(default=None, to='wasserman_core.contact'),
        ),
    ]
