# Generated by Django 4.2.6 on 2024-03-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0050_remove_agency_contact_id_alter_agency_date_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.contact'),
        ),
    ]
