# Generated by Django 4.2.6 on 2024-03-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0051_remove_agency_contact_id_agency_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusiTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasserman_core.business')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.player')),
            ],
        ),
    ]
