# Generated by Django 4.2.6 on 2024-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0052_busitargets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busitargets',
            name='player',
        ),
        migrations.AddField(
            model_name='busitargets',
            name='player',
            field=models.ManyToManyField(to='wasserman_core.player'),
        ),
    ]
