# Generated by Django 4.2.6 on 2024-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0053_remove_busitargets_player_busitargets_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='busitargets',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
