# Generated by Django 4.2.6 on 2024-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0055_remove_busitargets_player_busitargets_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='club',
            name='sponsors',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
    ]
