# Generated by Django 4.2.6 on 2024-03-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0056_club_address_club_phone_club_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='contact_id',
        ),
    ]
