# Generated by Django 4.2.6 on 2024-03-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasserman_core', '0057_remove_agency_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agency_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wasserman_core.agency'),
        ),
    ]
